spring:
  application:
    name: h2-test-demo
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL
    username:
    password:
    driver-class-name: org.h2.Driver
    schema: schema.sql
    data: data.sql

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mappers/*.xml
